<nav class="user-interface">
    <ul class="link-list">
        <li>
            <a class="button button-primary" href="/resto/index.php/booking">Réserver</a>
            <a class="button button-primary" href="/resto/index.php/order">Commander</a>
        </li>
        <li class="layout-right">
            <p class="welcome">Bonjour <strong>bb aa</strong> !</p>
            <a class="button button-primary" href="/resto/index.php/user/logout">Déconnexion</a>
        </li>
    </ul>
</nav>

<main>

    <h2><i class="fa fa-cutlery"></i> Réservation d'une table</h2>

    <form>
    <fieldset>
        <legend>Réservation d'une table</legend>

        <ul>
            <li>
                <label>Date de réservation</label>
                <select>

                    <option value></option>
                </select>
            </li>
            <li>
                <label>Nombre de couverts</label>
                <select>

                    <option value></option>
                </select>
            </li>

        </ul>


    </fieldset>
    </form>

</main>