
<?php require'header.php'; ?>


<nav class="user-interface">
    <ul class="link-list">
        <li>

          <?php
          if(!isset($_SESSION['mail'])) {

              echo '<li class="layout-right">';
              echo '<a class="button button-primary" href="login.phtml">Connexion</a>';
              echo '</li>';

              echo '<li>';
              echo '<a class="button button-primary" href="user.phtml">Créer un compte</a>';
              echo '</li>';


          }

       else {
           echo '<li>';
                   echo ' <a class="button button-primary" href="/resto/index.php/booking">Réserver</a>';
                   echo ' <a class="button button-primary" href="/resto/index.php/order">Commander</a>';
            echo ' </li>';
           echo ' <li class="layout-right">';
           echo '<p class="welcome">Bonjour <strong>'.$_SESSION['lastName'].'</strong> !</p>';
           echo ' <a class="button button-primary" href="logout.php">Deconnexion</a>';
       echo ' </li>';
         }
       ?>



    </ul>
</nav>

    <main>



        <!-- Affichage du template lié à la vue -->
        <table class="generic-table meal-list">
            <?php
            while ($articles=$req->fetch())
            {
                ?>
            <caption>Carte du restaurant</caption>
            <tbody>
            <tr>
                <td><img src="images/manger/<?=$articles['id_product'],'.', $articles['extension']?>"> </td>
                <td>
                    <strong><?= $articles['title_product']?> </strong>
                    <p><?= $articles['description']?></p>
                </td>
                <td class="number"><strong> <?= $articles['price_ttc']?></strong> €</td>

            </tr>
            </tbody>
            <?php
            }
            ?>
        </table>
    </main>

    <!-- Pied de page commun -->
    <?php require 'footer.php'; ?>