
<?php require'header.php'; ?>


    <!-- Interface utilisateur -->
    <nav class="user-interface">
        <ul class="link-list">
            <li>
                <a class="button button-primary" href="/resto/index.php/user">Créer un compte</a>
            </li>
            <li class="layout-right">
                <a class="button button-primary" href="/resto/index.php/user/login">Connexion</a>
            </li>
        </ul>
    </nav>

    <main>
        <!-- Affichage du template lié à la vue -->
        <table class="generic-table meal-list">
            <caption>Carte du restaurant</caption>
            <tbody>
            <tr>
                <td><img src=""> </td>
                <td>
                    <strong></strong>
                    <p></p>
                </td>
                <td class="number"><strong> ?prix</strong> €</td>

            </tr>
            </tbody>
        </table>
    </main>

    <!-- Pied de page commun -->
    <?php require 'footer.php'; ?>