<?php require'header.php'; ?>

<main>

    <h2><i class="fa fa-lock"></i>Se connecter avec un compte utilisateur</h2>
    <form class="generic-form" method="POST">
    <fieldset>
        <legend>Informations d'authentification</legend>
        <ul>
            <li>
                <label for="mail">Email :</label>
                <input id="mail" name="mail" type="mail" data-required value="<?= $_POST['mail']?? '' ?>" >
            </li>
            <li>
                <label for="userPassword">Mot de passe :</label>
                <input id="userPassword" name="password" type="password" data-required value="<?= $_POST['password']?? '' ?>">
            </li>
        </ul>



    </fieldset>
    <ul>

        <li>

            <input  class="button button-primary" type="submit" value="Créer le compte">
            <a class="button button-cancel small" href="/resto/index.php">Annuler</a>
        </li>
    </ul>

    </form>


</main>

<?php require 'footer.php'; ?>