<?php

 require'header.php'; ?>

<nav class="user-interface">
    <ul class="link-list">
        <li>
            <a class="button button-primary" href="/resto/index.php/user">Créer un compte</a>
        </li>
        <li class="layout-right">
            <a class="button button-primary" href="/resto/index.php/user/login">Connexion</a>
        </li>
    </ul>
</nav>


<main>

    <h2><i class="fa fa-user"></i> Création d'un compte client</h2>
    <form>









    </form>








</main>