<?php

 require'header.php'; ?>




<main>

    <h2><i class="fa fa-user"></i> Création d'un compte client</h2>

    <form class="generic-form" method="POST">



                        <fieldset>
            <legend><i class="fa fa-book"></i> Identité et coordonnées</legend>
                <ul>



                    <li>
                        <label for="lastName">Nom :</label>
                        <input type="text" id="lastName" name="lastName" data-required value="<?= $_POST['lastName'] ?? '' ?>">
                    </li>

                    <li>
                        <label for="firstName">Prénom:</label>
                        <input type="text" id="firstName" name="firstName" data-required value="<?= $_POST['firstName'] ?? '' ?>" >
                    </li>

                    <li>
                        <label for="birthDate">Date de naissance :</label>
                        <input type="date" id="birthDate" name="birthdate" max="2017/05/05" min="2000/04/03" value="<?= $_POST['birthdate']?? '' ?>">
                    </li>

                    <li>
                        <label class="textarea" for="adress">Adresse :</label>
                        <textarea rows="3" id="adress" name="adress" value="<?= $_POST['adress']?? '' ?>" ></textarea>
                    </li>

                    <li>
                        <label for="city">Ville :</label>
                        <input type="text" id="city" name="city" value="<?= $_POST['city']?? '' ?>">
                    </li>

                    <li>
                        <label for="CP">Code Postal :</label>
                        <input class="zip-code" type="text" id="city" name="CP" maxlength="5" data-type="number" value="<?= $_POST['CP']?? '' ?>"  >
                    </li>

                    <li>
                        <label for="tel">Téléphone :</label>
                        <input type="tel" id="tel" name="tel" maxlength="10"  data-type="number" value="<?= $_POST['tel']?? '' ?>" >
                    </li>
                </ul>


        </fieldset>

        <fieldset>
            <legend><i class="fa fa-lock"></i> Informations d'authentification</legend>

                <ul>
                    <li>
                        <label for="mail">Email :</label>
                        <input id="mail" name="mail" type="mail" data-required value="<?= $_POST['mail']?? '' ?>" >
                    </li>
                    <li>
                        <label for="userPassword">Mot de passe :</label>
                        <input id="userPassword" name="password" type="password" data-required value="<?= $_POST['password']?? '' ?>">
                    </li>
                </ul>

        </fieldset>


            <ul>

                <li>

                    <input  class="button button-primary" type="submit" value="Créer le compte">
                    <a class="button button-cancel small" href="/resto/index.php">Annuler</a>
                </li>
            </ul>


    </form>


    <?php
    include_once"inc/sql.php";
    include_once 'inc/functions.php';

    $b = trimDatasPost($_POST);
    $editUser = $pdo->prepare('INSERT INTO `table_user` (`lastName`, `firstName`, `birthdate`, `adress`, `city`, `CP`, `tel`, `mail`, `password`) VALUES(?,?,?,?,?,?,?,?, SHA1(?))');

    $b_result = $editUser->execute(array_values($b));

    header ('location:index.php');

    ?>





</main>

<?php require 'footer.php'; ?>